import { useState, useEffect, useCallback } from "react";
import { ClipboardList, Plus, Send, RefreshCw, ChevronRight, X, Copy } from "lucide-react";
const API="http://localhost:8001";
const STATUS_CFG={ACTIVE:{color:"#34D399",label:"Active"},DRAFT:{color:"#94A3B8",label:"Draft"},ARCHIVED:{color:"#475569",label:"Archived"}};
const RESP_STATUS={COMPLETED:{color:"#34D399",label:"Completed"},IN_PROGRESS:{color:"#60A5FA",label:"In Progress"},PENDING:{color:"#FBBF24",label:"Pending"}};
const FW_OPTIONS=["SOC2","HIPAA","GDPR","PCI_DSS","ISO27001","NIST_CSF"];
function btn(bg,border){return{display:"flex",alignItems:"center",gap:6,padding:"9px 14px",background:bg,border:`1px solid ${border}`,borderRadius:8,color:"#94A3B8",fontSize:13,cursor:"pointer"};}
function ScoreBar({score}){if(!score)return<span style={{color:"#475569",fontSize:12}}>Pending</span>;const color=score>=80?"#34D399":score>=60?"#FBBF24":"#F87171";return(<div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:60,height:5,background:"#1E293B",borderRadius:3,overflow:"hidden"}}><div style={{width:`${score}%`,height:"100%",background:color,borderRadius:3}}/></div><span style={{color,fontSize:12,fontWeight:600}}>{score}%</span></div>);}
export default function QuestionnaireBuilder({token,tenantId}){
const[questionnaires,setQuestionnaires]=useState([]);
const[loading,setLoading]=useState(true);
const[selected,setSelected]=useState(null);
const[questions,setQuestions]=useState([]);
const[responses,setResponses]=useState([]);
const[view,setView]=useState("list");
const[showCreate,setShowCreate]=useState(false);
const[showSend,setShowSend]=useState(false);
const[form,setForm]=useState({title:"",description:"",frameworks:[]});
const[sendEmails,setSendEmails]=useState("");
const[sending,setSending]=useState(false);
const[copied,setCopied]=useState(false);
const fetch_=useCallback(async()=>{setLoading(true);try{const res=await fetch(`${API}/api/questionnaires?tenant_id=${tenantId||"demo"}`,{headers:{Authorization:`Bearer ${token}`}});const data=await res.json();setQuestionnaires(data.questionnaires||[]);}catch{setQuestionnaires([]);}finally{setLoading(false);}
},[token,tenantId]);
useEffect(()=>{fetch_();},[fetch_]);
const loadQ=async(q)=>{setSelected(q);setView("detail");try{const[qRes,rRes]=await Promise.all([fetch(`${API}/api/questionnaires/${q.id}/questions`,{headers:{Authorization:`Bearer ${token}`}}),fetch(`${API}/api/questionnaires/${q.id}/responses`,{headers:{Authorization:`Bearer ${token}`}})]);const qData=await qRes.json();const rData=await rRes.json();setQuestions(qData.questions||[]);setResponses(rData.responses||[]);}catch{}};
const createQ=async()=>{if(!form.title)return alert("Title required.");try{await fetch(`${API}/api/questionnaires?tenant_id=${tenantId||"demo"}`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(form)});setShowCreate(false);setForm({title:"",description:"",frameworks:[]});fetch_();}catch{alert("Failed");}};
const sendQ=async()=>{const emails=sendEmails.split(",").map(e=>e.trim()).filter(Boolean);if(!emails.length)return alert("Enter at least one email.");setSending(true);try{await fetch(`${API}/api/questionnaires/${selected.id}/send`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({emails})});alert(`✅ Sent to ${emails.length} recipients`);setShowSend(false);setSendEmails("");}catch{alert("Failed");}finally{setSending(false);}};
const copyLink=()=>{navigator.clipboard.writeText(`https://app.aura.io/q/${selected?.id}?token=demo`);setCopied(true);setTimeout(()=>setCopied(false),2000);};
const sections=[...new Set((questions||[]).map(q=>q.section))];
if(view==="detail"&&selected){return(<div style={{padding:"28px 32px"}}>
<button onClick={()=>{setView("list");setSelected(null);}} style={{display:"flex",alignItems:"center",gap:6,background:"none",border:"none",color:"#64748B",fontSize:13,cursor:"pointer",marginBottom:20,padding:0}}><ChevronRight size={14} style={{transform:"rotate(180deg)"}}/>Back</button>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:24}}>
<div><h2 style={{margin:0,fontSize:22,fontWeight:700,color:"#F1F5F9"}}>{selected.title}</h2><p style={{margin:"6px 0 0",color:"#64748B",fontSize:13}}>{selected.description}</p></div>
<div style={{display:"flex",gap:8}}><button onClick={copyLink} style={btn("#1E293B","#334155")}><Copy size={14}/>{copied?"Copied!":"Copy Link"}</button><button onClick={()=>setShowSend(true)} style={btn("#1E3A5F","#2563EB")}><Send size={14}/>Send</button></div>
</div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
<div>
<h3 style={{color:"#64748B",fontSize:12,textTransform:"uppercase",letterSpacing:".05em",marginBottom:12}}>Questions ({questions.length})</h3>
<div style={{display:"flex",flexDirection:"column",gap:8,maxHeight:500,overflowY:"auto"}}>
{sections.map(section=>(<div key={section}><div style={{color:"#A78BFA",fontSize:11,fontWeight:600,textTransform:"uppercase",letterSpacing:".05em",marginBottom:6,marginTop:8}}>{section}</div>{questions.filter(q=>q.section===section).map(q=>(<div key={q.id} style={{background:"#0F172A",border:"1px solid #1E293B",borderRadius:10,padding:"12px 14px",marginBottom:6}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:4}}><span style={{color:"#E2E8F0",fontSize:12,flex:1,lineHeight:1.5}}>{q.question}</span>{q.required&&<span style={{color:"#F87171",fontSize:10,marginLeft:8}}>Required</span>}</div><div style={{display:"flex",gap:8,marginTop:6}}><span style={{background:"rgba(99,102,241,.1)",color:"#818CF8",borderRadius:4,padding:"1px 6px",fontSize:10}}>{q.type==="yes_no"?"Yes/No":"Multiple Choice"}</span><span style={{color:"#475569",fontSize:10}}>{q.framework_ref}</span></div></div>))}</div>))}
</div>
</div>
<div>
<h3 style={{color:"#64748B",fontSize:12,textTransform:"uppercase",letterSpacing:".05em",marginBottom:12}}>Responses ({responses.length})</h3>
<div style={{display:"flex",flexDirection:"column",gap:8}}>
{responses.map(r=>{const sc=RESP_STATUS[r.status]||RESP_STATUS.PENDING;return(<div key={r.id} style={{background:"#0F172A",border:"1px solid #1E293B",borderRadius:12,padding:"14px 16px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:8}}><div><div style={{color:"#E2E8F0",fontSize:13,fontWeight:500}}>{r.respondent_name}</div><div style={{color:"#475569",fontSize:11}}>{r.respondent_email}</div></div><span style={{background:`${sc.color}18`,color:sc.color,borderRadius:5,padding:"2px 7px",fontSize:11,fontWeight:600}}>{sc.label}</span></div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><ScoreBar score={r.score}/><span style={{color:"#475569",fontSize:11}}>{r.answers}/{questions.length} answered</span></div></div>);})}
{responses.length===0&&<div style={{textAlign:"center",padding:40,color:"#475569",fontSize:13}}>No responses yet.</div>}
</div>
</div>
</div>
{showSend&&(<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,.75)",zIndex:1000,display:"flex",alignItems:"center",justifyContent:"center"}} onClick={e=>e.target===e.currentTarget&&setShowSend(false)}><div style={{background:"#0F172A",border:"1px solid #1E293B",borderRadius:16,padding:28,width:440}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:20}}><h3 style={{margin:0,color:"#F1F5F9",fontSize:17}}>Send Questionnaire</h3><button onClick={()=>setShowSend(false)} style={{background:"none",border:"none",color:"#475569",cursor:"pointer"}}><X size={18}/></button></div><label style={{display:"block",marginBottom:16}}><div style={{color:"#64748B",fontSize:12,marginBottom:5}}>Recipient Emails (comma separated)</div><textarea value={sendEmails} onChange={e=>setSendEmails(e.target.value)} rows={4} placeholder="security@company.com, ciso@vendor.io…" style={{width:"100%",background:"#1E293B",border:"1px solid #334155",borderRadius:8,padding:"9px 12px",color:"#F1F5F9",fontSize:13,resize:"vertical",boxSizing:"border-box"}}/></label><div style={{display:"flex",gap:10,justifyContent:"flex-end"}}><button onClick={()=>setShowSend(false)} style={btn("#1E293B","#334155")}>Cancel</button><button onClick={sendQ} disabled={sending} style={btn("#1E3A5F","#2563EB")}>{sending?"Sending…":<><Send size={14}/>Send</>}</button></div></div></div>)}
</div>);}
return(<div style={{padding:"28px 32px"}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:28}}><div><h2 style={{margin:0,fontSize:22,fontWeight:700,color:"#F1F5F9",display:"flex",alignItems:"center",gap:10}}><ClipboardList size={22} color="#34D399"/>Questionnaire Builder</h2><p style={{margin:"6px 0 0",color:"#64748B",fontSize:13}}>Build and send security questionnaires to customers and vendors</p></div><div style={{display:"flex",gap:10}}><button onClick={fetch_} style={btn("#1E293B","#334155")}><RefreshCw size={14}/>Refresh</button><button onClick={()=>setShowCreate(true)} style={btn("#0D2818","#16A34A")}><Plus size={14}/>New Questionnaire</button></div></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:14,marginBottom:24}}>{[{label:"Total",value:questionnaires.length,color:"#60A5FA"},{label:"Total Responses",value:questionnaires.reduce((a,q)=>a+q.responses_count,0),color:"#34D399"},{label:"Active",value:questionnaires.filter(q=>q.status==="ACTIVE").length,color:"#A78BFA"}].map(s=>(<div key={s.label} style={{background:"#0F172A",border:"1px solid #1E293B",borderRadius:12,padding:"16px 18px"}}><div style={{color:"#64748B",fontSize:12,marginBottom:8}}>{s.label}</div><div style={{fontSize:26,fontWeight:700,color:s.color}}>{s.value||0}</div></div>))}</div>
{loading?<div style={{textAlign:"center",padding:60,color:"#475569"}}><RefreshCw size={20} style={{animation:"spin 1s linear infinite"}}/></div>:(
<div style={{display:"flex",flexDirection:"column",gap:10}}>{questionnaires.map(q=>{const sc=STATUS_CFG[q.status]||STATUS_CFG.DRAFT;return(<div key={q.id} onClick={()=>loadQ(q)} style={{background:"#0F172A",border:"1px solid #1E293B",borderRadius:12,padding:"18px 20px",cursor:"pointer",transition:"border-color .15s",display:"grid",gridTemplateColumns:"1fr auto",alignItems:"center",gap:16}} onMouseEnter={e=>e.currentTarget.style.borderColor="#334155"} onMouseLeave={e=>e.currentTarget.style.borderColor="#1E293B"}><div><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:6}}><span style={{background:`${sc.color}18`,color:sc.color,borderRadius:5,padding:"2px 8px",fontSize:11,fontWeight:600}}>{sc.label}</span>{(q.frameworks||[]).map(f=><span key={f} style={{background:"rgba(59,130,246,.1)",color:"#60A5FA",borderRadius:4,padding:"1px 6px",fontSize:10}}>{f}</span>)}</div><div style={{color:"#E2E8F0",fontSize:15,fontWeight:600,marginBottom:4}}>{q.title}</div><div style={{color:"#64748B",fontSize:12,marginBottom:8}}>{q.description}</div><div style={{display:"flex",gap:16}}><span style={{color:"#475569",fontSize:12}}>{q.questions_count} questions</span><span style={{color:"#475569",fontSize:12}}>{q.responses_count} responses</span></div></div><ChevronRight size={16} color="#334155"/></div>);})}</div>)}
{showCreate&&(<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,.75)",zIndex:1000,display:"flex",alignItems:"center",justifyContent:"center"}} onClick={e=>e.target===e.currentTarget&&setShowCreate(false)}><div style={{background:"#0F172A",border:"1px solid #1E293B",borderRadius:16,padding:28,width:480}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:20}}><h3 style={{margin:0,color:"#F1F5F9",fontSize:17}}>New Questionnaire</h3><button onClick={()=>setShowCreate(false)} style={{background:"none",border:"none",color:"#475569",cursor:"pointer"}}><X size={18}/></button></div><label style={{display:"block",marginBottom:14}}><div style={{color:"#64748B",fontSize:12,marginBottom:5}}>Title *</div><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} style={{width:"100%",background:"#1E293B",border:"1px solid #334155",borderRadius:8,padding:"9px 12px",color:"#F1F5F9",fontSize:13,boxSizing:"border-box"}}/></label><label style={{display:"block",marginBottom:14}}><div style={{color:"#64748B",fontSize:12,marginBottom:5}}>Description</div><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={2} style={{width:"100%",background:"#1E293B",border:"1px solid #334155",borderRadius:8,padding:"9px 12px",color:"#F1F5F9",fontSize:13,resize:"vertical",boxSizing:"border-box"}}/></label><label style={{display:"block",marginBottom:20}}><div style={{color:"#64748B",fontSize:12,marginBottom:8}}>Frameworks</div><div style={{display:"flex",flexWrap:"wrap",gap:6}}>{FW_OPTIONS.map(f=><button key={f} onClick={()=>setForm(fm=>({...fm,frameworks:fm.frameworks.includes(f)?fm.frameworks.filter(x=>x!==f):[...fm.frameworks,f]}))} style={{padding:"3px 10px",borderRadius:5,fontSize:11,cursor:"pointer",border:form.frameworks.includes(f)?"1px solid #3B82F6":"1px solid #334155",background:form.frameworks.includes(f)?"rgba(59,130,246,.15)":"#1E293B",color:form.frameworks.includes(f)?"#60A5FA":"#64748B"}}>{f}</button>)}</div></label><div style={{display:"flex",gap:10,justifyContent:"flex-end"}}><button onClick={()=>setShowCreate(false)} style={btn("#1E293B","#334155")}>Cancel</button><button onClick={createQ} style={btn("#0D2818","#16A34A")}><Plus size={14}/>Create</button></div></div></div>)}
<style>{`@keyframes spin{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}`}</style>
</div>);}
