import { useState, useEffect, useCallback } from "react";
import { FileBarChart, Plus, Download, RefreshCw, X, BarChart2, TrendingUp, Shield, FileText } from "lucide-react";
const API="http://localhost:8001";
const FW_COLORS={SOC2:"#3b82f6",ISO27001:"#8b5cf6",RBI:"#f97316",DPDP:"#10b981",ALL:"#94a3b8"};
const TYPE_COLORS={"Readiness":"#3b82f6","Board":"#8b5cf6","Gap Analysis":"#ef4444","Audit Package":"#10b981","Executive":"#f59e0b","Evidence":"#06b6d4","Summary":"#94a3b8"};

const sty={
  hdr:{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:24},
  h2:{fontSize:20,fontWeight:800,color:"#e2e8f0",display:"flex",alignItems:"center",gap:10,margin:0},
  sub:{color:"#475569",fontSize:13,marginTop:4},
  btnGhost:{display:"flex",alignItems:"center",gap:6,padding:"8px 16px",background:"rgba(139,92,246,0.08)",border:"1px solid rgba(139,92,246,0.2)",borderRadius:9,color:"#a78bfa",fontSize:13,fontWeight:600,cursor:"pointer"},
  btnPrimary:{display:"flex",alignItems:"center",gap:6,padding:"8px 18px",background:"linear-gradient(135deg,#7c3aed,#6d28d9)",border:"none",borderRadius:9,color:"#fff",fontSize:13,fontWeight:700,cursor:"pointer"},
  card:{background:"#111827",border:"1px solid rgba(139,92,246,0.08)",borderRadius:14,padding:"20px 22px",marginBottom:10},
  modal:{position:"fixed",inset:0,background:"rgba(0,0,0,0.7)",backdropFilter:"blur(4px)",zIndex:100,display:"flex",alignItems:"center",justifyContent:"center",padding:20},
  modalBox:{background:"#111827",border:"1px solid rgba(139,92,246,0.2)",borderRadius:16,padding:28,width:"100%",maxWidth:460},
  field:{marginBottom:14},
  lbl:{display:"block",fontSize:10,fontWeight:700,color:"#94a3b8",marginBottom:5,textTransform:"uppercase",letterSpacing:".5px"},
  inp:{width:"100%",background:"#1a2235",border:"1px solid rgba(139,92,246,0.15)",borderRadius:8,padding:"9px 12px",color:"#e2e8f0",fontSize:13,outline:"none",fontFamily:"inherit",boxSizing:"border-box"},
};

function ScoreRing({score,size=52}){
  const r=size/2-5; const circ=2*Math.PI*r; const dash=circ*(score/100);
  const color=score>=80?"#10b981":score>=60?"#f59e0b":"#ef4444";
  return(
    <svg width={size} height={size}>
      <circle cx={size/2} cy={size/2} r={r} fill="none" stroke="rgba(255,255,255,0.06)" strokeWidth="5"/>
      <circle cx={size/2} cy={size/2} r={r} fill="none" stroke={color} strokeWidth="5" strokeDasharray={`${dash} ${circ}`} strokeLinecap="round" transform={`rotate(-90 ${size/2} ${size/2})`}/>
      <text x={size/2} y={size/2+4} textAnchor="middle" fill={color} fontSize="12" fontWeight="700">{score}%</text>
    </svg>
  );
}

function generatePDF(report, data) {
  const w=window.open("","_blank");
  if(!w)return alert("Allow popups to download reports.");
  const s=data.summary||{};
  const fwRows=(data.framework_scores||[]).map(f=>`<tr><td>${f.framework}</td><td>${f.score}%</td><td>${f.controls} controls</td></tr>`).join("");
  const gapRows=(data.top_gaps||[]).map(g=>`<tr><td>${g.control}</td><td>${g.framework}</td><td style="color:${g.priority==="CRITICAL"?"#ef4444":"#f97316"}">${g.priority}</td><td>${g.status}</td></tr>`).join("");
  const html=`<!DOCTYPE html><html><head><title>${report.name}</title><style>body{font-family:sans-serif;padding:40px;color:#1e293b;max-width:900px;margin:auto}h1{font-size:26px}h2{font-size:17px;border-bottom:2px solid #e2e8f0;padding-bottom:8px;margin-top:28px}.header{background:#0f172a;color:#fff;padding:28px;border-radius:10px;margin-bottom:28px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:24px}.card{background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:14px;text-align:center}.num{font-size:26px;font-weight:700}.lbl{font-size:11px;color:#64748b;margin-top:4px}table{width:100%;border-collapse:collapse}th{background:#f1f5f9;padding:9px 13px;text-align:left;font-size:11px;font-weight:600;text-transform:uppercase}td{padding:9px 13px;border-bottom:1px solid #e2e8f0;font-size:13px}</style></head><body>
  <div class="header"><h1 style="margin:0;color:#fff">${report.name}</h1><p style="color:#94a3b8;margin:6px 0 0">${report.period} · Generated by AURA GRC Platform</p></div>
  <h2>Executive Summary</h2>
  <div class="grid">
    <div class="card"><div class="num">${s.overall_score}%</div><div class="lbl">Overall Score</div></div>
    <div class="card"><div class="num">${s.controls_implemented}/${s.controls_total}</div><div class="lbl">Controls</div></div>
    <div class="card"><div class="num" style="color:#dc2626">${s.critical_risks}</div><div class="lbl">Critical Risks</div></div>
    <div class="card"><div class="num">${s.evidence_approved}/${s.evidence_total}</div><div class="lbl">Evidence</div></div>
  </div>
  <h2>Framework Scores</h2><table><thead><tr><th>Framework</th><th>Score</th><th>Controls</th></tr></thead><tbody>${fwRows}</tbody></table>
  <h2>Top Gaps</h2><table><thead><tr><th>Control</th><th>Framework</th><th>Priority</th><th>Status</th></tr></thead><tbody>${gapRows}</tbody></table>
  <script>window.onload=()=>window.print();</script></body></html>`;
  w.document.write(html); w.document.close();
}

export default function Reports({token,tenantId}){
  const[reports,setReports]=useState([]);
  const[loading,setLoading]=useState(true);
  const[showGen,setShowGen]=useState(false);
  const[generating,setGenerating]=useState(false);
  const[form,setForm]=useState({name:"",framework:"SOC2",type:"Readiness",period:new Date().toLocaleString("default",{month:"long",year:"numeric"})});

  const load=useCallback(async()=>{
    setLoading(true);
    try{const res=await fetch(`${API}/api/reports?tenant_id=${tenantId||"demo"}`,{headers:{Authorization:`Bearer ${token}`}});const d=await res.json();setReports(d.reports||[]);}
    catch{setReports([]);}
    setLoading(false);
  },[token,tenantId]);
  useEffect(()=>{load();},[load]);

  const generate=async()=>{
    setGenerating(true);
    try{
      const name=form.name||`${form.framework} ${form.type} — ${form.period}`;
      const res=await fetch(`${API}/api/reports/generate?tenant_id=${tenantId||"demo"}`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({...form,name,generated_by:"Current User"})});
      const data=await res.json();
      if(data.report)generatePDF(data.report,data.data||{});
      setShowGen(false); load();
    }catch{alert("Generation failed");}
    setGenerating(false);
  };

  const download=async(r)=>{
    try{const res=await fetch(`${API}/api/reports/${r.id}/download?tenant_id=${tenantId||"demo"}`,{headers:{Authorization:`Bearer ${token}`}});const data=await res.json();generatePDF(r,data||{});}
    catch{alert("Download failed");}
  };

  return(
    <div>
      <div style={sty.hdr}>
        <div>
          <h2 style={sty.h2}><FileBarChart size={20} color="#8b5cf6"/>Compliance Reports</h2>
          <p style={sty.sub}>Generate board-ready PDF reports · Gap analysis · Audit packages · Executive summaries</p>
        </div>
        <div style={{display:"flex",gap:10}}>
          <button onClick={load} style={sty.btnGhost}><RefreshCw size={13}/>Refresh</button>
          <button onClick={()=>setShowGen(true)} style={sty.btnPrimary}><Plus size={13}/>Generate Report</button>
        </div>
      </div>

      <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:24}}>
        {[{i:<FileText size={18}/>,l:"Total Reports",v:reports.length,c:"#8b5cf6"},{i:<BarChart2 size={18}/>,l:"This Month",v:reports.filter(r=>new Date(r.created_at)>new Date(Date.now()-30*86400000)).length,c:"#3b82f6"},{i:<TrendingUp size={18}/>,l:"Avg Score",v:`${Math.round(reports.reduce((a,r)=>a+(r.overall_score||0),0)/(reports.length||1))}%`,c:"#10b981"},{i:<Shield size={18}/>,l:"Frameworks",v:new Set(reports.map(r=>r.framework)).size,c:"#f97316"}].map(st=>(
          <div key={st.l} style={{...sty.card,padding:"18px 20px",position:"relative",overflow:"hidden"}}>
            <div style={{position:"absolute",top:0,left:0,right:0,height:3,background:st.c}}/>
            <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start"}}>
              <div>
                <div style={{fontSize:24,fontWeight:800,color:st.c}}>{st.v}</div>
                <div style={{fontSize:11,color:"#475569",textTransform:"uppercase",letterSpacing:".5px",marginTop:2}}>{st.l}</div>
              </div>
              <div style={{color:st.c,opacity:.6}}>{st.i}</div>
            </div>
          </div>
        ))}
      </div>

      {loading?<div style={{textAlign:"center",padding:60,color:"#475569"}}><RefreshCw size={20} style={{animation:"spin 1s linear infinite"}}/></div>:(
        <div>
          {reports.length===0&&<div style={{...sty.card,textAlign:"center",padding:60,color:"#475569"}}><FileBarChart size={32} style={{opacity:.3,margin:"0 auto 12px"}}/><p>No reports yet. Generate your first report above.</p></div>}
          {reports.map(r=>{
            const fc=FW_COLORS[r.framework]||"#8b5cf6";
            const tc=TYPE_COLORS[r.type]||"#94a3b8";
            return(
              <div key={r.id} style={{...sty.card,display:"flex",alignItems:"center",gap:16}}>
                <ScoreRing score={r.overall_score||0}/>
                <div style={{flex:1,minWidth:0}}>
                  <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:6}}>
                    <span style={{background:fc+"20",color:fc,borderRadius:100,padding:"2px 10px",fontSize:11,fontWeight:700}}>{r.framework}</span>
                    <span style={{background:tc+"20",color:tc,borderRadius:100,padding:"2px 10px",fontSize:11,fontWeight:600}}>{r.type}</span>
                  </div>
                  <div style={{fontSize:14,fontWeight:600,color:"#e2e8f0",marginBottom:2}}>{r.name}</div>
                  <div style={{fontSize:12,color:"#475569"}}>{r.period} · {r.pages} pages · {new Date(r.created_at).toLocaleDateString("en-IN")}</div>
                </div>
                <button onClick={()=>download(r)} style={sty.btnGhost}><Download size={13}/>Download PDF</button>
              </div>
            );
          })}
        </div>
      )}

      {showGen&&(
        <div style={sty.modal} onClick={e=>e.target===e.currentTarget&&setShowGen(false)}>
          <div style={sty.modalBox}>
            <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}>
              <h3 style={{margin:0,color:"#e2e8f0",fontSize:16,fontWeight:700}}>Generate Report</h3>
              <button onClick={()=>setShowGen(false)} style={{background:"none",border:"none",color:"#475569",cursor:"pointer"}}><X size={18}/></button>
            </div>
            <div style={sty.field}>
              <label style={sty.lbl}>Report Name (optional)</label>
              <input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Auto-generated if empty" style={sty.inp}/>
            </div>
            <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>
              <div style={sty.field}>
                <label style={sty.lbl}>Framework</label>
                <select value={form.framework} onChange={e=>setForm({...form,framework:e.target.value})} style={sty.inp}>
                  {["SOC2","ISO27001","RBI","DPDP","ALL"].map(f=><option key={f}>{f}</option>)}
                </select>
              </div>
              <div style={sty.field}>
                <label style={sty.lbl}>Report Type</label>
                <select value={form.type} onChange={e=>setForm({...form,type:e.target.value})} style={sty.inp}>
                  {["Readiness","Board","Gap Analysis","Audit Package","Executive","Evidence","Summary"].map(t=><option key={t}>{t}</option>)}
                </select>
              </div>
            </div>
            <div style={sty.field}>
              <label style={sty.lbl}>Period</label>
              <input value={form.period} onChange={e=>setForm({...form,period:e.target.value})} style={sty.inp}/>
            </div>
            <div style={{display:"flex",gap:10,justifyContent:"flex-end",marginTop:4}}>
              <button onClick={()=>setShowGen(false)} style={{...sty.btnGhost,color:"#475569"}}>Cancel</button>
              <button onClick={generate} disabled={generating} style={sty.btnPrimary}>{generating?"Generating…":"Generate & Download"}</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
