import { useState, useEffect, useCallback } from "react";
import { FileBarChart, Plus, Download, RefreshCw } from "lucide-react";
const API="http://localhost:8000";
const FRAMEWORK_COLORS={SOC2:"#60A5FA",HIPAA:"#34D399",GDPR:"#A78BFA",PCI_DSS:"#F87171",ISO27001:"#FBBF24",NIST_CSF:"#6EE7B7",ALL:"#94A3B8"};
const TYPE_COLORS={"Readiness":"#60A5FA","Board":"#A78BFA","Gap Analysis":"#F87171","Audit Package":"#34D399","Executive":"#FBBF24","Vendor Risk":"#FB923C","Evidence":"#6EE7B7","Summary":"#94A3B8"};
function btn(bg,border){return{display:"flex",alignItems:"center",gap:6,padding:"9px 14px",background:bg,border:`1px solid ${border}`,borderRadius:8,color:"#94A3B8",fontSize:13,cursor:"pointer"};}
function ScoreRing({score,size=56}){const r=size/2-6;const circ=2*Math.PI*r;const dash=circ*(score/100);const color=score>=80?"#34D399":score>=60?"#FBBF24":"#F87171";return(<svg width={size} height={size}><circle cx={size/2} cy={size/2} r={r} fill="none" stroke="#1E293B" strokeWidth="5"/><circle cx={size/2} cy={size/2} r={r} fill="none" stroke={color} strokeWidth="5" strokeDasharray={`${dash} ${circ}`} strokeLinecap="round" transform={`rotate(-90 ${size/2} ${size/2})`}/><text x={size/2} y={size/2+5} textAnchor="middle" fill={color} fontSize="13" fontWeight="700">{score}%</text></svg>);}
function generatePDF(report,data){
const w=window.open("","_blank");
if(!w)return alert("Please allow popups to download reports.");
const fwRows=(data.framework_scores||[]).map(f=>`<tr><td>${f.framework}</td><td><div style="display:flex;align-items:center;gap:8px"><div style="width:${f.score*1.5}px;height:10px;background:${f.score>=80?"#34D399":f.score>=60?"#FBBF24":"#F87171"};border-radius:5px"></div>${f.score}%</div></td><td>${f.controls} controls</td></tr>`).join("");
const gapRows=(data.top_gaps||[]).map(g=>`<tr><td>${g.control}</td><td>${g.framework}</td><td style="color:${g.priority==="CRITICAL"?"#EF4444":g.priority==="HIGH"?"#F87171":"#FBBF24"}">${g.priority}</td><td>${g.status.replace(/_/g," ")}</td></tr>`).join("");
const s=data.summary||{};
const html=`<!DOCTYPE html><html><head><title>${report.name}</title><style>body{font-family:'Segoe UI',Arial,sans-serif;margin:0;padding:40px;color:#1E293B;max-width:900px;margin:auto}h1{color:#0F172A;font-size:28px;margin-bottom:4px}h2{color:#334155;font-size:18px;margin:32px 0 12px;border-bottom:2px solid #E2E8F0;padding-bottom:8px}.header{background:linear-gradient(135deg,#0F172A,#1E293B);color:#fff;padding:32px;border-radius:12px;margin-bottom:32px}.header h1{color:#fff;margin:0 0 8px}.meta{color:#94A3B8;font-size:13px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:32px}.card{background:#F8FAFC;border:1px solid #E2E8F0;border-radius:10px;padding:16px;text-align:center}.num{font-size:28px;font-weight:700;color:#0F172A}.lbl{font-size:12px;color:#64748B;margin-top:4px}table{width:100%;border-collapse:collapse;margin-bottom:24px}th{background:#F1F5F9;padding:10px 14px;text-align:left;font-size:12px;color:#475569;font-weight:600;text-transform:uppercase}td{padding:10px 14px;border-bottom:1px solid #E2E8F0;font-size:13px}.footer{margin-top:40px;padding-top:16px;border-top:1px solid #E2E8F0;color:#94A3B8;font-size:12px;display:flex;justify-content:space-between}</style></head><body>
<div class="header"><h1>${report.name}</h1><div class="meta">Generated by ${report.generated_by} · Period: ${report.period} · ${new Date(data.generated_at).toLocaleDateString("en-IN",{day:"2-digit",month:"long",year:"numeric"})}</div></div>
<h2>Executive Summary</h2>
<div class="grid">
<div class="card"><div class="num" style="color:${s.overall_score>=80?"#16A34A":s.overall_score>=60?"#D97706":"#DC2626"}">${s.overall_score}%</div><div class="lbl">Overall Score</div></div>
<div class="card"><div class="num">${s.controls_implemented}/${s.controls_total}</div><div class="lbl">Controls Implemented</div></div>
<div class="card"><div class="num" style="color:#DC2626">${s.critical_risks}</div><div class="lbl">Critical Risks</div></div>
<div class="card"><div class="num">${s.evidence_approved}/${s.evidence_total}</div><div class="lbl">Evidence Approved</div></div>
</div>
<h2>Framework Compliance Scores</h2>
<table><thead><tr><th>Framework</th><th>Score</th><th>Controls</th></tr></thead><tbody>${fwRows}</tbody></table>
<h2>Top Compliance Gaps</h2>
<table><thead><tr><th>Control</th><th>Framework</th><th>Priority</th><th>Status</th></tr></thead><tbody>${gapRows}</tbody></table>
<h2>Additional Metrics</h2>
<div class="grid">
<div class="card"><div class="num">${s.vendors_total}</div><div class="lbl">Total Vendors</div></div>
<div class="card"><div class="num" style="color:#DC2626">${s.vendors_high_risk}</div><div class="lbl">High Risk Vendors</div></div>
<div class="card"><div class="num">${s.policies_approved}/${s.policies_total}</div><div class="lbl">Policies Approved</div></div>
<div class="card"><div class="num" style="color:#D97706">${s.evidence_expiring}</div><div class="lbl">Evidence Expiring</div></div>
</div>
<div class="footer"><span>AURA GRC Platform — Confidential</span><span>Page 1 of ${report.pages||1}</span></div>
<script>window.onload=()=>window.print();</script>
</body></html>`;
w.document.write(html);w.document.close();}
export default function Reports({token,tenantId}){
const[reports,setReports]=useState([]);
const[templates,setTemplates]=useState([]);
const[loading,setLoading]=useState(true);
const[showGenerate,setShowGenerate]=useState(false);
const[generating,setGenerating]=useState(false);
const[downloading,setDownloading]=useState(false);
const[form,setForm]=useState({name:"",framework:"SOC2",type:"Readiness",period:new Date().toLocaleString("default",{month:"long",year:"numeric"})});
const fetch_=useCallback(async()=>{
setLoading(true);
try{
const[rRes,tRes]=await Promise.all([fetch(`${API}/api/reports?tenant_id=${tenantId||"demo"}`,{headers:{Authorization:`Bearer ${token}`}}),fetch(`${API}/api/reports/templates`,{headers:{Authorization:`Bearer ${token}`}})]);
const rData=await rRes.json();const tData=await tRes.json();
setReports(rData.reports||[]);setTemplates(tData.templates||[]);
}catch{setReports([]);}finally{setLoading(false);}
},[token,tenantId]);
useEffect(()=>{fetch_();},[fetch_]);
const generateReport=async()=>{
setGenerating(true);
try{
const name=form.name||`${form.framework} ${form.type} — ${form.period}`;
const res=await fetch(`${API}/api/reports/generate?tenant_id=${tenantId||"demo"}`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({...form,name,generated_by:"Current User"})});
const data=await res.json();
setShowGenerate(false);setReports(r=>[data.report,...r]);
}catch{alert("Generation failed");}finally{setGenerating(false);}};
const downloadReport=async(report)=>{
setDownloading(true);
try{
const res=await fetch(`${API}/api/reports/${report.id}/data?tenant_id=${tenantId||"demo"}`,{headers:{Authorization:`Bearer ${token}`}});
const data=await res.json();
generatePDF(report,data);
}catch{alert("Download failed");}finally{setDownloading(false);}};
const FW_OPTIONS=["SOC2","HIPAA","GDPR","PCI_DSS","ISO27001","NIST_CSF","ALL"];
const TYPE_OPTIONS=["Readiness","Board","Gap Analysis","Audit Package","Executive","Vendor Risk","Evidence","Summary"];
return(<div style={{padding:"28px 32px"}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:28}}>
<div><h2 style={{margin:0,fontSize:22,fontWeight:700,color:"#F1F5F9",display:"flex",alignItems:"center",gap:10}}><FileBarChart size={22} color="#6EE7B7"/>Reports</h2><p style={{margin:"6px 0 0",color:"#64748B",fontSize:13}}>Generate and export board-ready compliance reports</p></div>
<div style={{display:"flex",gap:10}}><button onClick={fetch_} style={btn("#1E293B","#334155")}><RefreshCw size={14}/>Refresh</button><button onClick={()=>setShowGenerate(true)} style={btn("#0D2818","#16A34A")}><Plus size={14}/>Generate Report</button></div>
</div>
<h3 style={{color:"#64748B",fontSize:12,textTransform:"uppercase",letterSpacing:".05em",marginBottom:12}}>Report Templates</h3>
<div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12,marginBottom:28}}>
{templates.map(t=>(<div key={t.id} onClick={()=>{setForm({name:t.name,framework:t.frameworks[0]==="ALL"?"SOC2":t.frameworks[0],type:t.name,period:new Date().toLocaleString("default",{month:"long",year:"numeric"})});setShowGenerate(true);}} style={{background:"#0F172A",border:"1px solid #1E293B",borderRadius:12,padding:16,cursor:"pointer",transition:"border-color .15s"}} onMouseEnter={e=>e.currentTarget.style.borderColor="#334155"} onMouseLeave={e=>e.currentTarget.style.borderColor="#1E293B"}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:8}}><span style={{color:"#E2E8F0",fontSize:13,fontWeight:600}}>{t.name}</span><span style={{color:"#475569",fontSize:11}}>~{t.pages_est}p</span></div>
<div style={{color:"#64748B",fontSize:12,marginBottom:10}}>{t.description}</div>
<div style={{display:"flex",flexWrap:"wrap",gap:4}}>{t.frameworks.slice(0,3).map(f=><span key={f} style={{background:`${FRAMEWORK_COLORS[f]||"#94A3B8"}18`,color:FRAMEWORK_COLORS[f]||"#94A3B8",borderRadius:4,padding:"2px 6px",fontSize:10}}>{f}</span>)}</div>
</div>))}
</div>
<h3 style={{color:"#64748B",fontSize:12,textTransform:"uppercase",letterSpacing:".05em",marginBottom:12}}>Generated Reports</h3>
{loading?<div style={{textAlign:"center",padding:40,color:"#475569"}}><RefreshCw size={20} style={{animation:"spin 1s linear infinite"}}/></div>:(
<div style={{display:"flex",flexDirection:"column",gap:10}}>
{reports.map(r=>{const fc=FRAMEWORK_COLORS[r.framework]||"#94A3B8";const tc=TYPE_COLORS[r.type]||"#94A3B8";const score=r.score||0;const scoreColor=score>=80?"#34D399":score>=60?"#FBBF24":"#F87171";
return(<div key={r.id} style={{background:"#0F172A",border:"1px solid #1E293B",borderRadius:12,padding:"16px 20px",display:"grid",gridTemplateColumns:"auto 1fr auto auto",gap:16,alignItems:"center"}} onMouseEnter={e=>e.currentTarget.style.borderColor="#334155"} onMouseLeave={e=>e.currentTarget.style.borderColor="#1E293B"}>
<ScoreRing score={score}/>
<div>
<div style={{display:"flex",alignItems:"center",gap:8,marginBottom:4}}><span style={{background:`${fc}18`,color:fc,borderRadius:5,padding:"2px 7px",fontSize:11,fontWeight:600}}>{r.framework}</span><span style={{background:`${tc}18`,color:tc,borderRadius:5,padding:"2px 7px",fontSize:11}}>{r.type}</span></div>
<div style={{color:"#E2E8F0",fontSize:14,fontWeight:600,marginBottom:2}}>{r.name}</div>
<div style={{color:"#475569",fontSize:12}}>By {r.generated_by} · {r.period} · {r.pages} pages</div>
</div>
<div style={{textAlign:"right"}}><div style={{color:scoreColor,fontSize:20,fontWeight:700}}>{score}%</div><div style={{color:"#475569",fontSize:11}}>compliance</div></div>
<button onClick={()=>downloadReport(r)} disabled={downloading} style={{...btn("#0D2818","#16A34A"),flexShrink:0}}><Download size={14}/>{downloading?"…":"Download PDF"}</button>
</div>);})}
{reports.length===0&&<div style={{textAlign:"center",padding:40,color:"#475569",fontSize:13}}>No reports yet.</div>}
</div>)}
{showGenerate&&(<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,.75)",zIndex:1000,display:"flex",alignItems:"center",justifyContent:"center"}} onClick={e=>e.target===e.currentTarget&&setShowGenerate(false)}>
<div style={{background:"#0F172A",border:"1px solid #1E293B",borderRadius:16,padding:28,width:460}}>
<h3 style={{margin:"0 0 20px",color:"#F1F5F9",fontSize:17}}>Generate Report</h3>
<label style={{display:"block",marginBottom:14}}><div style={{color:"#64748B",fontSize:12,marginBottom:5}}>Report Name</div><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Auto-generated if blank" style={{width:"100%",background:"#1E293B",border:"1px solid #334155",borderRadius:8,padding:"9px 12px",color:"#F1F5F9",fontSize:13,boxSizing:"border-box"}}/></label>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginBottom:14}}>
<label><div style={{color:"#64748B",fontSize:12,marginBottom:5}}>Framework</div><select value={form.framework} onChange={e=>setForm({...form,framework:e.target.value})} style={{width:"100%",background:"#1E293B",border:"1px solid #334155",borderRadius:8,padding:"9px 12px",color:"#F1F5F9",fontSize:13}}>{FW_OPTIONS.map(o=><option key={o}>{o}</option>)}</select></label>
<label><div style={{color:"#64748B",fontSize:12,marginBottom:5}}>Report Type</div><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})} style={{width:"100%",background:"#1E293B",border:"1px solid #334155",borderRadius:8,padding:"9px 12px",color:"#F1F5F9",fontSize:13}}>{TYPE_OPTIONS.map(o=><option key={o}>{o}</option>)}</select></label>
</div>
<label style={{display:"block",marginBottom:20}}><div style={{color:"#64748B",fontSize:12,marginBottom:5}}>Period</div><input value={form.period} onChange={e=>setForm({...form,period:e.target.value})} style={{width:"100%",background:"#1E293B",border:"1px solid #334155",borderRadius:8,padding:"9px 12px",color:"#F1F5F9",fontSize:13,boxSizing:"border-box"}}/></label>
<div style={{display:"flex",gap:10,justifyContent:"flex-end"}}><button onClick={()=>setShowGenerate(false)} style={btn("#1E293B","#334155")}>Cancel</button><button onClick={generateReport} disabled={generating} style={btn("#0D2818","#16A34A")}>{generating?"Generating…":<><FileBarChart size={14}/>Generate</>}</button></div>
</div></div>)}
<style>{`@keyframes spin{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}`}</style>
</div>);}
